### ISSUE TITLE
CPFs inválidos podem ser cadastrados.

### ISSUE THREAD

**Issue by EliAndrade** [NathanMB/LabEng#11]
![Capturar](https://user-images.githubusercontent.com/33854332/78725555-3427a700-7906-11ea-9b80-d77013d5bf84.PNG)

CPFs inválidos podem ser cadastrados, como letras e números fora do formato. O que pode ser feito é passar um Regex antes ser inserido no BD.

**Comment by harrison-santos** [comment]
Vou precisar que o front faça algum tipo de tratamento de input, provavelmente utilizando js, e depois vai ser feito outro tratamento no back.  @Vonttech

**Comment by Vonttech** [comment]
Vou providenciar.

**Comment by Vonttech** [comment]
Vou providenciar

**Comment by Vonttech** [comment]
Resolvido
