### ISSUE TITLE
Gráfico inicial com borda vermelha

### ISSUE THREAD

**Issue by NathanMB** [NathanMB/LabEng#36]
![Anotação 2020-05-01 205815](https://user-images.githubusercontent.com/37597728/80850104-a717fb00-8bf0-11ea-9ab0-cadcc36ef6e5.png)

**Comment by EliAndrade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[3pt] [Sprint 6] Adicionar gráficos ao HomePage](https://trello.com/c/sQmkwWix/72-3pt-sprint-6-adicionar-gr%C3%A1ficos-ao-homepage)

**Comment by Vonttech** [comment]
Resolvido
