### ISSUE TITLE
Campos preenchidos de forma errada não apresentam erro

### ISSUE THREAD

**Issue by NathanMB** [NathanMB/LabEng#39]
![Anotação 2020-05-01 210638](https://user-images.githubusercontent.com/37597728/80850206-1db4f880-8bf1-11ea-9859-e8c2a6f6cf91.png)
Caso algum campo de cadastrar paciente não seja atendido, não está aparecendo mensagem de erro.

**Comment by EliAndrade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[3pt] Implementação Cadastro de Paciente](https://trello.com/c/onNPw2Bb/45-3pt-implementa%C3%A7%C3%A3o-cadastro-de-paciente)

**Comment by EliAndrade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[3pt] Implementação Cadastro de Paciente](https://trello.com/c/onNPw2Bb/45-3pt-implementa%C3%A7%C3%A3o-cadastro-de-paciente)

**Comment by EliAndrade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[3pt] [Sprint 5] Tela de alteração de Perfil](https://trello.com/c/CerZ8UuE/73-3pt-sprint-5-tela-de-altera%C3%A7%C3%A3o-de-perfil)

**Comment by EliAndrade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[3pt] [Sprint 5] Tela de alteração de Perfil](https://trello.com/c/CerZ8UuE/73-3pt-sprint-5-tela-de-altera%C3%A7%C3%A3o-de-perfil)

**Comment by Vonttech** [comment]
Resolvido
