### ISSUE TITLE
Botões sobrepostos em listar exame

### ISSUE THREAD

**Issue by EliAndrade** [NathanMB/LabEng#41]
Botões ficam sobrepostos quando há uma recomendação maior que o esperado.

![Capturar](https://user-images.githubusercontent.com/33854332/80850313-9ae06d80-8bf1-11ea-89f2-24f9bef46ce7.PNG)

**Comment by EliAndrade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [1 - Correção de Listagem de Exame](https://trello.com/c/D1uTz1rm/71-1-corre%C3%A7%C3%A3o-de-listagem-de-exame)

**Comment by Vonttech** [comment]
Corrigido
