### ISSUE TITLE
Exames permite selecionar datas inválidas

### ISSUE THREAD

**Issue by NathanMB** [NathanMB/LabEng#42]
![Anotação 2020-05-01 213728](https://user-images.githubusercontent.com/37597728/80850775-00355e00-8bf4-11ea-9d47-5fd386b9b4c8.png)

Exames permitindo selecionar datas inválida

**Comment by EliAndrade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[4pt][Sprint 6] Correção Tela de Cadastro de Exame](https://trello.com/c/v8tHlSaB/70-4ptsprint-6-corre%C3%A7%C3%A3o-tela-de-cadastro-de-exame)

**Comment by EliAndrade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[3pt] Tela de Cadastro de Exame](https://trello.com/c/yjkSWbGQ/43-3pt-tela-de-cadastro-de-exame)

**Comment by EliAndrade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[3pt] Tela de Cadastro de Exame](https://trello.com/c/yjkSWbGQ/43-3pt-tela-de-cadastro-de-exame)

**Comment by Vonttech** [comment]
Resolvido
