### ISSUE TITLE
Botões Deletar e Cadastrar saindo do quadro

### ISSUE THREAD

**Issue by EliAndrade** [NathanMB/LabEng#7]
![Capturar](https://user-images.githubusercontent.com/33854332/78724357-a8ad1680-7903-11ea-904a-185c00dcdf16.PNG)

Os botões saem do quadro quando há uma recomendação grande. Pode ser necessário truncar tamanho da recomendação e criar uma página de visualização de detalhes de exame.

**Comment by Vonttech** [comment]
Corrigido. Também foi corrigido o background desproporcional ao reduzir demasiadamente a tela do dispositivo.
