### ISSUE TITLE
Médico responsável pelo Exame

### ISSUE THREAD

**Issue by NathanMB** [NathanMB/LabEng#8]
![1](https://user-images.githubusercontent.com/37597728/78724451-e14cf000-7903-11ea-9b08-1b17c1086cb9.PNG)

Na tela de cadastro de exames não tem a opção de colocar o médico responsável pelo exame cadastrado.

**Comment by Vonttech** [comment]
Parcialmente resolvido, o back-end precisa alterar o comando do formulário para a exibição do nome do médico.

**Comment by harrison-santos** [comment]
Todos os exames cadastros vão se vincular ao médico logado. Não há necessidade de um campo para  selecionar médico.

**Comment by harrison-santos** [comment]
Campo removido
